In [2]:
import numpy as np

In [6]:
print(np.random.randn(5, 3)*0.1)

[[-0.19004386 -0.21638705 -0.1412161 ]
 [ 0.11032176  0.11323612 -0.12318135]
 [-0.01621264  0.09344102  0.05872784]
 [ 0.18970328  0.02596785  0.02363618]
 [ 0.17804998 -0.04614065 -0.16905522]]


In [ ]:
def init_layers(nn_architecture, seed = 99):
    np.random.seed(seed)
    number_of_layers = len(nn_architecture)
    params_values={}
    
    for idx, layer in enumerate(nn_architecture):
        layer_idx = idx + 1
        layer_input_size = layer["input_dim"]
        layer_output_size = layer["output_dim"]
        params_values['W' + str(layer_idx)] = np.random.randn(layer_output_size, layer_input_size)*0.1
        params_values['b' + str(layer_idx)] = np.random.randn(layer_output_size, 1) * 0.1
    
    return params_values